[api]
api_url="https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add"

[s3]
bucket='wcd-assignments'
folder='chapter3'

[db]
host='cwljh0xfrdkt.us-east-1.rds.amazonaws.com'
port=3306
database='wcd-assignments'
schema='superstore'

[run]
py_script="etl.py"